from django.urls import path, include # used to include the list of urls in urlpatterns and asssigning the list to a specific url
# This is the model we created and is in our local directory
from profiles_api import views
# For accesing viewsets we require Routers
from rest_framework.routers import DefaultRouter


# First of we register "'/whatever'--> Opens a page with APIs of HelloViewSet" to the router
router = DefaultRouter()
router.register('hello-viewset', views.HelloViewSet, base_name='hello_viewset')


urlpatterns = [
    path('hello-view/', views.HelloApiView.as_view()),# as_view() is call
    path('', include(router.urls)) # Here include all the urls generated by router to carry on the request made by HelloViewSet class
    # '' represents that when ever 'api/' is hit we'll get all the urls given by router ready at disposal
]
