# Generated by Django 2.2 on 2020-02-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='user_profil',
            new_name='user_profile',
        ),
    ]
